### ISSUE TITLE
pandoc extension?

### ISSUE THREAD

**Issue by ousia** [bpj/bpj-pandoc-scripts#1]
HI @bpj,

I guess that changing the file extension from `.pandoc` to `.md` (or even `.markdown`) in the documents in the `doc/` directory would make the documents more readable when displayed by GitHub.

At least, `pandoc` is a program. `markdown` is the format. But sorry if this was intended.

**Comment by bpj** [comment]
It's intentional since those files use pandoc-specific extensions -- mainly definition lists and metadata blocks which make them unsuitable to view through Github's markdown renderer. They are also meant to be processed by my commit-hook script, including having some parts of their metadata inserted into the text and being converted to Github markdown with pandoc for the repository wiki. You can read the docs properly assembled and formatted for Github in the wiki (link in the right sidebar.) If I had remembered to commit the templates I use to process those `.pandoc` files that had perhaps been clearer. I'll put a readme in the doc directory when I get home.
